openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
  contact:
    email: contact@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description:Sample API demo
tags:
  - name: Demo
    description: Example of apis
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  '/users/{username}':
    $ref: 'users@{username}.yaml'
  '/updateusers/{username}':
    $ref: 'updateusers@{username}.yaml'
  '/getusers/{username}':
    $ref: 'getusers@{username}.yaml'
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
